spring.application.name=Tasks App
spring.output.ansi.enabled=ALWAYS

# http://localhost:8080/h2/login.jsp
# JDBC URL: jdbc:h2:mem:tasks-app
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.url=jdbc:h2:mem:tasks-app
